# Generated by Django 3.2.7 on 2021-09-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=30)),
                ('weather_description', models.CharField(max_length=30)),
                ('temp', models.FloatField()),
                ('temp_feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
            ],
        ),
    ]
