# Generated by Django 3.2.7 on 2021-10-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_cityweatherinfo_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cityweatherinfo',
            unique_together={('city_name', 'date')},
        ),
    ]
