# Generated by Django 3.2.7 on 2021-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_cityweatherinfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweatherinfo',
            name='icon',
            field=models.CharField(default='01d', max_length=30),
        ),
    ]
