# Generated by Django 3.2.7 on 2021-10-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_cityweatherinfo_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweatherinfo',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
