# Generated by Django 3.2.7 on 2021-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_cityweatherinfo_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweatherinfo',
            name='icon',
            field=models.CharField(default='maral', max_length=20),
            preserve_default=False,
        ),
    ]
