version: '3'


services:
  mysql:
    container_name: 'WeatherPortal-MySQL'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_USERNAME: 'root'
    ports:
      - '3306:3306'
