version: '3'


services:
  mysql:
    container_name: 'WeatherPortal-MySQL'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_USERNAME: 'root'
    ports:
      - '3306:3306'

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - '5432:5432'
